### ISSUE TITLE
Binders have no access to the config

### ISSUE THREAD

**Issue by plenderyou** [ef-labs/vertx-jersey#38]
I cannot find a way to get the config passed into the verticle to be available in the binders.

**Comment by adrianluisgonzalez** [comment]
Can you provide an example of what you are trying to do?

One option is to use `bindFactory()` in your binder.  The HK2 [Factory](https://hk2.java.net/apidocs/org/glassfish/hk2/api/Factory.html)  can have the `Vertx` instance injected in the constructor allowing you to access the JSON configuration.

**Comment by meshuga** [comment]
`Vertx.currentContext().config()` should be sufficient. A thread maintained by Vert.x always has a reference to a processing context and its configuration.

**Comment by adrianluisgonzalez** [comment]
+1 @meshuga
