### ISSUE TITLE
Add another exemple that starts from the vertx Get Started docs

### ISSUE THREAD

**Issue by bric3** [ef-labs/vertx-jersey#49]
The Vert.x _getting started_ documentation points to some [hello-world maven project](https://github.com/vert-x3/vertx-examples/tree/master/maven-simplest).

I'd like to setup a JAX-RS contract from the hello-world project via this module, and I find the documentation confusing to setup the JAX-RS verticle from that very first vert.x example (starts a `main` and configure programmatically `vertx`). I believe the README could be improved in that matter without using the maven service (in a real project for example we tend to migrate bit by bit the code).

**Comment by adrianluisgonzalez** [comment]
I have added a vertx-jersery version of [maven-simplest](https://github.com/ef-labs/vertx-jersey/tree/develop/examples/maven-simplest).

Does that help?

**Comment by bric3** [comment]
YES, thank you ! :)

You should mention that in the readme ;)
