### ISSUE TITLE
Do you know how could I load vertx config.json in a class out of the scope of a Verticle

### ISSUE THREAD

**Issue by pjgg** [ef-labs/vertx-jersey#50]
When I am using vertx-jersey, I don't need to start any verticle because is done by default by "Vertx-jersey". As a result of that I don't have any "Init App Context" where I can load some static values as default properties...etc 

Do you know how could I read vertx config.json from a class that it's not a rest resource?

**Comment by adrianluisgonzalez** [comment]
You can inject the `vertx` instance and access `vertx.config()` from any class.

This could be done in an `org.glassfish.jersey.server.spi.ContainerLifecycleListener` which has `onStartup(Container container)`.

**Comment by pjgg** [comment]
Ok!!! :) 

Also I did a walkaround. Basically I wrote a config.json without a "guice_binder" and than I start my app pointing to my verticle:

run java-guice:org.pablo.configuration.GuiceVerticleConf -conf config.json

And then in my "GuiceVerticleConf" class I just load all the properties in singleton property class

public class GuiceVerticleConf extends AbstractVerticle {
 @Override
    public void start(Future<Void> startedResult) {
        LOG.info("Main Verticle start!");

        //LOADING PROPERTIES
        Constants.loadValues(context);

        DeploymentOptions deploymentOptions = new DeploymentOptions();
        JsonObject jsonConfig = context.config();
        jsonConfig.put("guice_binder","org.pablo.configuration.CustomBinder");
        deploymentOptions.setConfig(jsonConfig);
        vertx.deployVerticle("java-guice:com.englishtown.vertx.jersey.JerseyVerticle", deploymentOptions);
    }
}

So then I can access to any property through  a simple static import

import static org.pablo.util.Constants.REDIS_HOST;
import static org.pablo.util.Constants.REDIS_PORT;

public class RedisConnectionModule extends AbstractModule{

	@Override
	protected void configure() {

        install(new GuiceJerseyBinder());

        RedisURI redisUri = RedisURI.Builder.redis(REDIS_HOST).withPort(REDIS_PORT).build();
        .
        .
        .

        
But of course your approach it's very smooth!. 

Thank Adrian!
