### ISSUE TITLE
cannot get the content of “text/xml“

### ISSUE THREAD

**Issue by xionghsiyan** [ef-labs/vertx-jersey#52]
在Vertx-jersey项目中，不能获取到text/xml的内容，application/xml和text/plain都可以获取到，经过查找发现是DefaultJerseyHandler的shouldRead方法中没有对text/xml这种类型进行处理，请予以解决。

**Comment by adrianluisgonzalez** [comment]
From Google translate:

> In the Vertx-jersey project, you can not get the contents of text / xml, application / xml and text / plain can be found, through the discovery is DefaultJerseyHandler shouldRead method does not text / xml this type of processing, please give solve.

**Comment by mikaelkaron** [comment]
I'll throw in a bing translation along the way

> In the Vertx-Jersey project, can not get to Text Xml content, Application Xml and filetype are available, after finding that Defaultjerseyhandler Shouldread method does not deal with this type, please resolve.

**Comment by xionghsiyan** [comment]
How can I replace "DefaultJerseyHandler" with my own "JerseyHandler" in vertx.jersey project?
