### ISSUE TITLE
Is there a way to start a JerseyServer easily? 

### ISSUE THREAD

**Issue by yingqiaomxi** [ef-labs/vertx-jersey#57]
I can start a JerseyServer by following the maven-service example. I wonder if there is an example to show how to start a JerseyServer from a main verticle? 
We are not using config.json... In this case, can we use JerseyVerticle? How can we do that?

**Comment by yingqiaomxi** [comment]
This is what I got at the end:

/**
 * {@link com.englishtown.vertx.jersey.promises.WhenJerseyServer} example
 */
public class StartupVerticle extends AbstractVerticle {

    /**
     * {@inheritDoc}
     */
    @Override
    public void start(Future<Void> aFuture) throws Exception {

        config()
            .put("jersey", new JsonObject()
                .put("host", "0.0.0.0")
                .put("port", 8085)
                .put("base_path","/")
                .put("packages", new JsonArray()
                    .add(HelloWorldEndpoint.class.getPackage().getName())
                    .add(HelloWorldEndpoint2.class.getPackage().getName())));

        // Use a service locator (HK2 or Guice are supported by default) to create the jersey server
        ServiceLocator locator = ServiceLocatorUtilities.bind(new HK2JerseyBinder(), new HK2VertxBinder(vertx));
        JerseyServer jerseyServer = locator.getService(JerseyServer.class);

        // Start the server which simply returns "Hello World!" to each GET request.
        jerseyServer.start(aResult->{
            if (aResult.succeeded()){
                aFuture.complete();
            }else{
                aFuture.fail(aResult.cause());
            }
        });
    }
}

I am not sure whether this is a correct way to start a JerseyServer or not. One issue is that I can not set "resources" in config(). I have to add each resource to packages...

**Comment by adrianluisgonzalez** [comment]
Two options:

1. Deploy `JerseyVerticle` from your main verticle.  Provide the configuration in the vert.x `DeploymentOptions` like this: `vertx.deployVerticle("java-hk2:com.englishtown.vertx.JerseyVerticle", options)`
2. Programmatically deploy the `JerseyServer` as is done in the `JerseyVerticle` [here](https://github.com/ef-labs/vertx-jersey/blob/develop/vertx-jersey/src/main/java/com/englishtown/vertx/jersey/JerseyVerticle.java#L52) or if you want to provide configuration you can use the `JerseyServer#start` overload that takes `JerseyServerOptions` and `JerseyOptions` [here](https://github.com/ef-labs/vertx-jersey/blob/develop/vertx-jersey/src/main/java/com/englishtown/vertx/jersey/JerseyServer.java#L82)

**Comment by yingqiaomxi** [comment]
Great! I will try the first option then.

**Comment by yingqiaomxi** [comment]
I made the version working now: 
/**
 * {@link com.englishtown.vertx.jersey.promises.WhenJerseyServer} example
 */
public class StartupVerticle extends AbstractVerticle {

    /**
     * {@inheritDoc}
     */
    @Override
    public void start(Future<Void> aFuture) throws Exception {

        DeploymentOptions options = new DeploymentOptions().setConfig(
                new JsonObject().put("jersey", new JsonObject()
                        .put("host", "0.0.0.0")
                        .put("port", 8085)
                        .put("resources", new JsonArray()
                                .add(HelloWorldEndpoint.class.getPackage().getName()))
                        .put("hk2_binder", "com.englishtown.vertx.hk2.HK2JerseyBinder")));

        vertx.deployVerticle("java-hk2:"+ JerseyVerticle.class.getName(), options);
    }
}

One question is that aFuture is not completed in this case. Is it OK?

**Comment by adrianluisgonzalez** [comment]
Use the `Vertx#deployVerticle` [overload](http://vertx.io/docs/apidocs/io/vertx/core/Vertx.html#deployVerticle-java.lang.String-io.vertx.core.DeploymentOptions-io.vertx.core.Handler-) with a callback to complete the future.

**Comment by yingqiaomxi** [comment]
Yes, many thanks!
