### ISSUE TITLE
How to register a Feature in JerseyVerticle?

### ISSUE THREAD

**Issue by yingqiaomxi** [ef-labs/vertx-jersey#59]
In Jersey, we may use ResourceConfig to register a Feature.class. I wonder how I can do that in a vertx-jersey application?

**Comment by adrianluisgonzalez** [comment]
Two options:

1. Via [configuration](https://github.com/ef-labs/vertx-jersey#configuration)
`components` - An array of components class names to inject (features, etc.). For example: `org.glassfish.jersey.jackson.JacksonFeature`.
2.  Programmatically by injecting an [ApplicationConfigurator](https://github.com/ef-labs/vertx-jersey/blob/develop/vertx-jersey/src/main/java/com/englishtown/vertx/jersey/ApplicationConfigurator.java)

**Comment by yingqiaomxi** [comment]
I see. How can I set up the configuration? For example, for a LoggingFeature, I may need to set up the logging level. How can I do that? 
Many thanks!

**Comment by adrianluisgonzalez** [comment]
Read through the rest of the configuration section in the README.  I think what you are looking for is  `properties`
properties - An object with additional properties to be set on the ResourceConfig

https://github.com/jersey/jersey/blob/master/core-common/src/main/java/org/glassfish/jersey/logging/LoggingFeature.java#L265

**Comment by yingqiaomxi** [comment]
Yes, this is helpful!
