### ISSUE TITLE
SockJS Handler

### ISSUE THREAD

**Issue by andrefilipegsilva** [ef-labs/vertx-jersey#72]
Evening,

Is it possible to configure a route for the SockJS Handler on the same port as Jersey? As in

```java
Router router = Router.router(vertx);

SockJSHandler sockJSHandler = SockJSHandler.create(vertx);
BridgeOptions options = new BridgeOptions();
sockJSHandler.bridge(options);

router.route("/eventbus/*").handler(sockJSHandler);
```

I've been working with the method `JerseyServer.setupHandler(Handler<HttpServer>)` but I cannot add any route to the requestHandler.

Regards.

**Comment by adrianluisgonzalez** [comment]
This was originally written before `vertx-web` existed and routes were done a little differently.

I think one way to achieve what you are after is to inject a custom `JerseyHandler` delegate that can inspect the path in `JerseyHandler#handle`.  If it is a path for Jersey then delegate to the `DefaultJerseyHandler`, if it is a path for the `Router` then call `router#accept`.  Something like that.

**Comment by andrefilipegsilva** [comment]
Got it, though it is a little intriguing because it clearly says on `JerseyServer.setupHandler(Handler<HttpServer>)`'s javadoc: 

"Allows custom setup during initialization before the http server is listening (add custom routes, etc.)"

Thus my doubt. I'll see what I can do.

**Comment by adrianluisgonzalez** [comment]
Agreed, at this point the comment is misleading.
